apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark
  namespace: urban-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark
  template:
    metadata:
      labels:
        app: spark
    spec:
      containers:
      - name: spark
        image: apache/spark:3.5.0
        command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.master.Master"]
        ports:
        - containerPort: 7077
        - containerPort: 8080
        env:
        - name: SPARK_MODE
          value: "master"
        - name: SPARK_RPC_AUTHENTICATION_ENABLED
          value: "no"